### ISSUE TITLE
what's the PHP minium requirement version ?

### ISSUE THREAD

**Issue by jaswdr** [rodolfobarretoweb/php-pdf-filler#1]
Hi, what's the PHP minimum required version ? I see that you use array() and PHP 5.5> it's a good practive to use [ ] instead, because use less memory.

**Comment by rodolfobarretoweb** [comment]
Thank you for Jaschweder suggestion. On the compatibility of php, I unfortunately not yet tested it, but looking at the used functions, I believe is fully compatible with all versions of PHP 5.
